locals {
  name_prefix   = "${var.project_name}-${var.environment}"
  full_zip      = "${path.root}/../dist/lambda.zip"
  api_subdomain = "api.${var.domain_name}"

  # Use the full zip (with pip deps) when it exists.
  # Fall back to the source-only zip generated by archive_file so that
  # `terraform plan/apply` works before `make build` has been run.
  lambda_zip_path = can(filebase64sha256(local.full_zip)) ? local.full_zip : data.archive_file.lambda_source.output_path
  lambda_zip_hash = can(filebase64sha256(local.full_zip)) ? filebase64sha256(local.full_zip) : data.archive_file.lambda_source.output_base64sha256

  routes = {
    "GET /posts"           = {}
    "GET /posts/{id}"      = {}
    "GET /search"          = {}
    "POST /posts"          = {}
    "PUT /posts/{id}"      = {}
    "DELETE /posts/{id}"   = {}
    "POST /auth/register"  = {}
    "POST /auth/login"     = {}
    "POST /images/upload"  = {}
    "OPTIONS /{proxy+}"    = {}
  }
}

# Packages source code only (no pip deps). Used as a bootstrap zip when
# dist/lambda.zip hasn't been built yet so terraform plan never fails on a
# missing file. The backend CI workflow replaces this with the full zip.
data "archive_file" "lambda_source" {
  type        = "zip"
  source_dir  = "${path.root}/../backend"
  output_path = "${path.root}/../dist/lambda_source.zip"
  excludes    = ["tests", "dist", "requirements.txt", "requirements-dev.txt", ".pytest_cache"]
}

# --- IAM ---

resource "aws_iam_role" "lambda" {
  name = "${local.name_prefix}-lambda"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "lambda" {
  name = "${local.name_prefix}-lambda-policy"
  role = aws_iam_role.lambda.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "dynamodb:GetItem", "dynamodb:PutItem", "dynamodb:UpdateItem",
          "dynamodb:DeleteItem", "dynamodb:Query", "dynamodb:Scan"
        ]
        Resource = [var.dynamodb_table_arn, "${var.dynamodb_table_arn}/index/*"]
      },
      {
        Effect   = "Allow"
        Action   = ["s3:PutObject", "s3:GetObject"]
        Resource = "${var.images_bucket_arn}/*"
      },
      {
        Effect   = "Allow"
        Action   = "ssm:GetParameter"
        Resource = "arn:aws:ssm:${var.aws_region}:*:parameter/${var.project_name}/${var.environment}/*"
      },
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"
        ]
        Resource = "arn:aws:logs:*:*:*"
      }
    ]
  })
}

# --- SSM: JWT secret ---

resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

resource "aws_ssm_parameter" "jwt_secret" {
  name  = "/${var.project_name}/${var.environment}/jwt-secret"
  type  = "SecureString"
  value = random_password.jwt_secret.result

  lifecycle {
    ignore_changes = [value] # Allow manual rotation without Terraform overwriting it
  }
}

# --- CloudWatch ---

resource "aws_cloudwatch_log_group" "lambda" {
  name              = "/aws/lambda/${local.name_prefix}-api"
  retention_in_days = 14
}

resource "aws_cloudwatch_log_group" "api_gateway" {
  name              = "/aws/apigateway/${local.name_prefix}"
  retention_in_days = 30
}

resource "aws_sns_topic" "alerts" {
  name = "${local.name_prefix}-alerts"
}

resource "aws_sns_topic_subscription" "email_alert" {
  topic_arn = aws_sns_topic.alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

resource "aws_cloudwatch_metric_alarm" "lambda_errors" {
  alarm_name          = "${local.name_prefix}-lambda-errors"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "Errors"
  namespace           = "AWS/Lambda"
  period              = 300
  statistic           = "Sum"
  threshold           = 5
  alarm_description   = "Lambda error rate exceeded 5 in 5 minutes"
  alarm_actions       = [aws_sns_topic.alerts.arn]

  dimensions = {
    FunctionName = aws_lambda_function.api.function_name
  }
}

# --- Lambda ---

resource "aws_lambda_function" "api" {
  function_name = "${local.name_prefix}-api"
  role          = aws_iam_role.lambda.arn
  runtime       = "python3.12"
  handler       = "handler.lambda_handler"
  architectures = ["arm64"]
  memory_size   = 256
  timeout       = 30

  filename         = local.lambda_zip_path
  source_code_hash = local.lambda_zip_hash

  environment {
    variables = {
      ENVIRONMENT      = var.environment
      DYNAMODB_TABLE   = var.dynamodb_table_name
      IMAGES_BUCKET    = var.images_bucket_id
      IMAGES_CDN_DOMAIN = "images.${var.domain_name}"
      PROJECT_NAME     = var.project_name
    }
  }

  depends_on = [aws_cloudwatch_log_group.lambda]
}

# --- API Gateway HTTP API v2 ---

resource "aws_apigatewayv2_api" "main" {
  name          = "${local.name_prefix}-api"
  protocol_type = "HTTP"

  cors_configuration {
    allow_origins = ["https://${var.domain_name}", "https://www.${var.domain_name}"]
    allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers = ["Content-Type", "Authorization"]
    max_age       = 86400
  }
}

resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.main.id
  name        = "$default"
  auto_deploy = true

  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.api_gateway.arn
    format = jsonencode({
      requestId      = "$context.requestId"
      ip             = "$context.identity.sourceIp"
      routeKey       = "$context.routeKey"
      status         = "$context.status"
      responseLength = "$context.responseLength"
      durationMs     = "$context.integrationLatency"
    })
  }
}

resource "aws_lambda_permission" "api_gateway" {
  statement_id  = "AllowAPIGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.api.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.main.execution_arn}/*/*"
}

resource "aws_apigatewayv2_integration" "lambda" {
  api_id                 = aws_apigatewayv2_api.main.id
  integration_type       = "AWS_PROXY"
  integration_uri        = aws_lambda_function.api.invoke_arn
  payload_format_version = "2.0"
}

resource "aws_apigatewayv2_route" "routes" {
  for_each = local.routes

  api_id    = aws_apigatewayv2_api.main.id
  route_key = each.key
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

# --- Custom domain for API ---

resource "aws_apigatewayv2_domain_name" "api" {
  domain_name = local.api_subdomain

  domain_name_configuration {
    certificate_arn = var.certificate_arn
    endpoint_type   = "REGIONAL"
    security_policy = "TLS_1_2"
  }
}

resource "aws_apigatewayv2_api_mapping" "api" {
  api_id      = aws_apigatewayv2_api.main.id
  domain_name = aws_apigatewayv2_domain_name.api.id
  stage       = aws_apigatewayv2_stage.default.id
}

resource "aws_route53_record" "api" {
  zone_id = var.zone_id
  name    = local.api_subdomain
  type    = "A"

  alias {
    name                   = aws_apigatewayv2_domain_name.api.domain_name_configuration[0].target_domain_name
    zone_id                = aws_apigatewayv2_domain_name.api.domain_name_configuration[0].hosted_zone_id
    evaluate_target_health = false
  }
}
